import { useState } from 'react';
import {
  Sparkles, AlertCircle, Copy, Check,
  FileText, BrainCircuit, PenTool,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { streamSummary } from '../services/api';
import { Button } from '../components/Button';
import { DropZone } from '../components/DropZone';
import { LoaderOverlay } from '../components/LoaderOverlay';

export default function SummarizerPage() {
  const [file, setSummaryFile]  = useState<File | null>(null);
  const [summary, setSummary]   = useState('');
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState('');
  const [copied, setCopied]     = useState(false);
  const [streaming, setStreaming] = useState(false);

  const handleSummarize = async () => {
    if (!file) return;
    setError('');
    setSummary('');
    setLoading(true);
    setStreaming(true);

    try {
      let accumulated = '';
      for await (const token of streamSummary(file)) {
        accumulated += token;
        setSummary(accumulated);
      }
    } catch (e: any) {
      setError(e.message ?? 'Summary failed. Check backend connection.');
    } finally {
      setLoading(false);
      setStreaming(false);
    }
  };

  const handleCopy = () => {
    if (!summary) return;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleClear = () => {
    setSummaryFile(null);
    setSummary('');
    setError('');
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 max-w-7xl mx-auto w-full pb-10 animate-fade-in">

      {/* ── Left column ─────────────────────────────────────────── */}
      <div className="lg:col-span-4 flex flex-col gap-5">
        <div className="relative bg-[#282828] border border-[#32302F] p-6 rounded-xl shadow-lg overflow-hidden">
          <LoaderOverlay isProcessing={loading} message="Generating Summary\u2026" />

          <div className="mb-5">
            <p className="font-mono text-xs text-[#7F986D] mb-2 tracking-wider">
              summarizer.module;
            </p>
            <h1 className="text-xl font-bold text-[#EFE7DF] flex items-center gap-2">
              <PenTool className="text-[#7F986D]" size={20} />
              Summarizer
            </h1>
            <p className="text-[#777068] text-sm mt-1.5">
              Condense long papers into structured academic summaries.
            </p>
          </div>

          <DropZone
            file={file}
            onFile={(f) => { setSummaryFile(f); setError(''); setSummary(''); }}
            onClear={handleClear}
            disabled={loading}
          />

          {error && (
            <div className="mt-4 flex items-start gap-2.5 p-3.5 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
              <AlertCircle size={16} className="flex-shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          <Button
            className="w-full mt-5"
            onClick={handleSummarize}
            disabled={!file || loading}
            isLoading={loading}
            icon={<Sparkles size={17} />}
          >
            Generate Summary
          </Button>
        </div>

        {/* Info card */}
        <div className="relative bg-[#282828] border border-[#32302F] rounded-xl p-6 overflow-hidden hidden lg:block">
          <BrainCircuit className="absolute -right-4 -bottom-4 w-28 h-28 text-[#7F986D]/5" />
          <h3 className="font-bold text-[#7F986D] mb-2">Fully local &amp; private</h3>
          <p className="text-[#777068] text-sm leading-relaxed">
            Summaries are generated by a locally running LLM. Your documents never leave your machine.
          </p>
        </div>
      </div>

      {/* ── Right column ────────────────────────────────────────── */}
      <div className="lg:col-span-8 flex flex-col min-h-[500px]">
        {/* Output header */}
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-base font-bold text-[#CFBFAD] flex items-center gap-2">
            <span className="w-1.5 h-5 bg-[#D9542C] rounded-full" />
            Output
            {streaming && (
              <span className="text-xs font-normal text-[#7F986D] animate-pulse ml-1 font-mono">
                &mdash; Generating&hellip;
              </span>
            )}
          </h2>
          {summary && !loading && (
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-lg bg-[#282828] border border-[#32302F] text-[#777068] hover:text-[#CFBFAD] hover:border-[#6A6156] transition-all"
            >
              {copied
                ? <><Check size={13} className="text-[#7F986D]" /> Copied</>
                : <><Copy size={13} /> Copy</>}
            </button>
          )}
        </div>

        {/* Output box */}
        <div className="flex-grow bg-[#282828] border border-[#32302F] rounded-xl p-7 overflow-y-auto shadow-xl">
          {loading && !summary ? (
            <div className="space-y-5 animate-pulse">
              <div className="h-4 bg-[#32302F] rounded w-1/3" />
              {[...Array(3)].map((_, i) => (
                <div key={i} className="space-y-2">
                  <div className="h-3 bg-[#32302F]/80 rounded w-full" />
                  <div className="h-3 bg-[#32302F]/80 rounded w-[90%]" />
                  <div className="h-3 bg-[#32302F]/80 rounded w-4/5" />
                </div>
              ))}
            </div>
          ) : summary ? (
            <div className="prose prose-invert prose-sm max-w-none
              prose-headings:text-[#7F986D] prose-headings:font-bold
              prose-p:text-[#CFBFAD] prose-p:leading-relaxed
              prose-li:text-[#CFBFAD]
              prose-strong:text-[#7F986D]
              prose-a:text-[#D9542C] prose-a:no-underline hover:prose-a:underline">
              <ReactMarkdown>{summary}</ReactMarkdown>
              {streaming && (
                <span className="inline-block w-2 h-4 bg-[#7F986D] animate-blink ml-0.5 rounded-sm align-middle" />
              )}
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-center opacity-30 select-none gap-4">
              <FileText className="w-14 h-14 text-[#777068]" />
              <div>
                <p className="text-[#777068] font-medium">No summary yet</p>
                <p className="text-[#777068] text-sm mt-1 max-w-xs">
                  Upload a PDF and click Generate to see the structured summary here.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
